version: "3.8"
services:
  postgres:
        container_name: postgres
        image: postgres
        #volumes: 
        #  - postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file: 
            - environment/.tsenv
  grafana:
        container_name: grafana
        image: grafana/grafana:latest
        restart: unless-stopped
        user: "1000"
        depends_on:
            - postgres
        ports:
            - 3000:3000
        env_file: environment/.gfenv
  pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:7.2
        environment:
          PGADMIN_DEFAULT_EMAIL: "artur.artur.smirnov3@gmail.com"
          PGADMIN_DEFAULT_PASSWORD: "artur"
          PGADMIN_CONFIG_SERVER_MODE: "False"
        ports:
          - "5050:80"
        #volumes:
        #  - pgadmin:/var/lib/pgadmin4/storage
        restart: unless-stopped
        deploy:
          resources:
            limits:
              cpus: '0.5'
              memory: 1G